source 'https://gitlab.enncloud.cn/FNMobileTeam/FNSpecRepos.git'

use_frameworks!

platform :ios, '8.0'

target 'FN_Macros_Example' do
  pod 'FN_Macros', :path => '../'

  target 'FN_Macros_Tests' do
    inherit! :search_paths
    
    
  end
end
